package:
  name: embedding_search
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja

  host:
    - python
    - pip !=22.1.0

  run:
    - python


test:
  requires:
    - pytest
  imports:
    - embedding_search
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  summary: Embedding search for python built with pybind11.
  license_file: LICENSE
